---
- name: install
  include_tasks: install.yml
  when: syslog_setup == "full"

- name: configuration
  include_tasks: configuration.yml

- name: setting installed flag
  set_fact:
    syslog_installed: true
